apiVersion: v1
data:
  kubernetes.conf: |2- 
    <label @FLUENT_LOG>
    <match fluent.**>
      @type null
    </match>
    </label>
   
    <source>
      @type tail
      @id in_tail_container_logs
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      tag "#{ENV['FLUENT_CONTAINER_TAIL_TAG'] || 'kubernetes.*'}"
      exclude_path "#{ENV['FLUENT_CONTAINER_TAIL_EXCLUDE_PATH'] || use_default}"
      read_from_head true
      <parse>
      @type "#{ENV['FLUENT_CONTAINER_TAIL_PARSER_TYPE'] || 'json'}"
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      </parse>
    </source>
   
    <filter kubernetes.**>
      @type kubernetes_metadata
      ca_file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file /var/run/secrets/kubernetes.io/serviceaccount/token
    </filter>
    
    <filter access>
      @type record_transformer
      <record>
      hostname "#{ENV['NODENAME']}"
      host "#{ENV['NODENAME']}"
      </record>
    </filter>
kind: ConfigMap
metadata:
  name: fluent-kubernetes-configmap
  namespace: kube-system
